ALTER TABLE [User]
ADD Document NVARCHAR(50) NULL;

ALTER TABLE [User]
ADD Name2 NVARCHAR(100) NULL;

ALTER TABLE [User]
ADD LastName NVARCHAR(100) NULL;

ALTER TABLE [User]
ADD IsDeleted BIT NOT NULL DEFAULT 0;

ALTER TABLE [User]
ADD IsConfirmed BIT NOT NULL DEFAULT 0;

ALTER TABLE [User]
ADD CreateDate DATETIME NOT NULL DEFAULT GETDATE(),
	UpdateDate DATETIME NOT NULL DEFAULT GETDATE();

ALTER TABLE [User]
ALTER COLUMN Document NVARCHAR(50) NOT NULL;

ALTER TABLE [User]
ADD CONSTRAINT UQ_User_Document_DocumentType UNIQUE (Document, DocumentTypeId);

ALTER TABLE [User]
ADD CONSTRAINT UQ_User_Email UNIQUE (Email);

SELECT * FROM [User]
